import { sql } from "drizzle-orm";
import {
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  vector,
} from "drizzle-orm/pg-core";

/**
 * Postgres `tsvector`. Drizzle has no built-in for it, and the column itself is
 * generated by the database rather than written by the application — see the
 * `.generatedAlwaysAs` below.
 */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});

export const docTypeEnum = pgEnum("doc_type", [
  "general",
  "client-brief",
  "meeting-note",
  "delivery-report",
  "changelog",
  "postmortem",
  "guide",
]);

export const documentStatusEnum = pgEnum("document_status", ["indexed", "failed", "deleted"]);

export const documents = pgTable(
  "documents",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** POSIX-style and relative to the corpus root. The ingestion diff's identity. */
    path: text("path").notNull(),
    title: text("title").notNull(),
    docType: docTypeEnum("doc_type").notNull().default("general"),
    /** Date parsed from the filename (`2026-03-...`), when present. */
    docDate: timestamp("doc_date", { withTimezone: true }),
    /** SHA-256 of the file bytes. Equal hash means skip — this is what makes re-ingest incremental. */
    contentHash: text("content_hash").notNull(),
    byteSize: integer("byte_size").notNull(),
    status: documentStatusEnum("status").notNull().default("indexed"),
    chunkCount: integer("chunk_count").notNull().default(0),
    lastError: text("last_error"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    indexedAt: timestamp("indexed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("documents_path_key").on(table.path),
    index("documents_status_idx").on(table.status),
    index("documents_doc_type_idx").on(table.docType),
  ],
);

export const chunks = pgTable(
  "chunks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    /** Position within the document, 0-based. */
    ordinal: integer("ordinal").notNull(),
    /** Heading breadcrumb, e.g. ["Delivery Report: Waffle Rush", "QA findings"]. */
    headingPath: text("heading_path").array().notNull().default(sql`ARRAY[]::text[]`),
    /** headingPath joined — denormalized so the generated tsvector can reference it. */
    headingText: text("heading_text").notNull().default(""),
    /** Chunk body. Citation offsets index into this exact string. */
    content: text("content").notNull(),
    tokenCount: integer("token_count").notNull().default(0),
    /** voyage-4 at its default 1024 dimensions. Changing this needs a migration + full re-ingest. */
    embedding: vector("embedding", { dimensions: 1024 }),
    /**
     * Lexical half of hybrid search. Generated by Postgres so it can never fall
     * out of sync with `content`, which a trigger or an application write could.
     */
    tsv: tsvector("tsv").generatedAlwaysAs(
      sql`to_tsvector('english', coalesce(heading_text, '') || ' ' || content)`,
    ),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("chunks_document_id_idx").on(table.documentId),
    uniqueIndex("chunks_document_ordinal_key").on(table.documentId, table.ordinal),
    // Both of the following are re-stated by hand in the migration SQL, because
    // drizzle-kit does not emit `USING hnsw` operator classes or GIN indexes on
    // a custom type. See .claude/skills/db-migrate.
    index("chunks_embedding_hnsw_idx").using("hnsw", table.embedding.op("vector_cosine_ops")),
    index("chunks_tsv_gin_idx").using("gin", table.tsv),
  ],
);

export type DocumentRow = typeof documents.$inferSelect;
export type NewDocumentRow = typeof documents.$inferInsert;
export type ChunkRow = typeof chunks.$inferSelect;
export type NewChunkRow = typeof chunks.$inferInsert;
